-- Создание таблицы "sensor"
CREATE TABLE sensor (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        name VARCHAR(255)
);

-- Создание таблицы "measurements"
CREATE TABLE measurements (
                              id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                              raining BOOLEAN,
                              value DOUBLE PRECISION,
                              created_at TIMESTAMP,
                              sensor_id INT,
                              FOREIGN KEY (sensor_id) REFERENCES sensor(id)
);